#pragma once

enum DMA_SINGLE_CHANNEL_MASK
{
    SEL0    = 0x01,
    SEL1    = 0x02,
    MASK_ON = 0x04
};

enum DMA_MULTICHANNEL_MASK
{
    MASK0 = 0x01,
    MASK1 = 0x02,
    MASK2 = 0x04,
    MASK3 = 0x08
};

enum DMA_TRANSFER_TYPE
{
    TYPE_SELF_TEST = 0x00,
    TYPE_WRITE_MEM = 0x01,
    TYPE_READ_MEM  = 0x02
};

enum DMA_TRANSFER_MODE
{
    MODE_ON_DEMAND = 0x00,
    MODE_SINGLE_TRANSFER = 0x01,
    MODE_BLOCK_TRANSFER = 0x02,
    MODE_CASCADE = 0x03
};

enum DMA_STATUS
{
    STATUS_REQUEST_PENDING_0 = 0x10,
    STATUS_REQUEST_PENDING_1 = 0x20,
    STATUS_REQUEST_PENDING_2 = 0x40,
    STATUS_REQUEST_PENDING_3 = 0x80,
    STATUS_TRANSFER_COMPLETE_0 = 0x01,
    STATUS_TRANSFER_COMPLETE_1 = 0x02,
    STATUS_TRANSFER_COMPLETE_2 = 0x04,
    STATUS_TRANSFER_COMPLETE_3 = 0x08
};

enum DMA_START_ADDR_PORTS 
{
    DMA_START_ADDR_CHANNEL_0 = 0x00,
    DMA_START_ADDR_CHANNEL_1 = 0x02,
    DMA_START_ADDR_CHANNEL_2 = 0x04,
    DMA_START_ADDR_CHANNEL_3 = 0x06,
    DMA_START_ADDR_CHANNEL_4 = 0xC0,
    DMA_START_ADDR_CHANNEL_5 = 0xC2,
    DMA_START_ADDR_CHANNEL_6 = 0xC4,
    DMA_START_ADDR_CHANNEL_7 = 0xC6
};

enum DMA_COUNT_REGISTER_PORTS
{
    DMA_COUNT_REGISTER_CHANNEL_0 = 0x01,
    DMA_COUNT_REGISTER_CHANNEL_1 = 0x03,
    DMA_COUNT_REGISTER_CHANNEL_2 = 0x05,
    DMA_COUNT_REGISTER_CHANNEL_3 = 0x07,
    DMA_COUNT_REGISTER_CHANNEL_4 = 0xC2,
    DMA_COUNT_REGISTER_CHANNEL_5 = 0xC6,
    DMA_COUNT_REGISTER_CHANNEL_6 = 0xCA,
    DMA_COUNT_REGISTER_CHANNEL_7 = 0xCE
};

enum DMA_CONTROL_REGISTER_PORTS
{
    DMA_STATUS_REGISTER_03 = 0x08,
    DMA_STATUS_REGISTER_47 = 0xD0,
    DMA_COMMAND_REGISTER_03 = 0x08,
    DMA_COMMAND_REGISTER_47 = 0xD0,
    DMA_REQUEST_REGISTER_03 = 0x09,
    DMA_REQUEST_REGISTER_47 = 0xD2,
    DMA_SINGLE_CHANNEL_MASK_REGISTER_03 = 0x0A,
    DMA_SINGLE_CHANNEL_MASK_REGISTER_47 = 0xD4,
    DMA_MODE_REGISTER_03 = 0x0B,
    DMA_MODE_REGISTER_47 = 0xD6,
    DMA_FLIP_FLOP_RESET_03 = 0x0C,
    DMA_FLIP_FLOP_RESET_47 = 0xD8,
    DMA_INTERMEDIATE_REGISTER_03 = 0x0D,
    DMA_INTERMEDIATE_REGISTER_47 = 0xDA,
    DMA_MASTER_RESET_REGISTER_03 = 0x0D,
    DMA_MASTER_RESET_REGISTER_47 = 0xDA,
    DMA_MASK_RESET_REGISTER_03 = 0x0E,
    DMA_MASK_RESET_REGISTER_47 = 0xDC,
    DMA_MULTICHANNEL_MASK_REGISTER_03 = 0x0F,
    DMA_MULTICHANNEL_MASK_REGISTER_47 = 0xDE,
};

enum DMA_PAGE_ADDR_PORTS
{
    DMA_PAGE_ADDR_CHANNEL_0 = 0x87,
    DMA_PAGE_ADDR_CHANNEL_1 = 0x83,
    DMA_PAGE_ADDR_CHANNEL_2 = 0x81,
    DMA_PAGE_ADDR_CHANNEL_3 = 0x82,
    DMA_PAGE_ADDR_CHANNEL_4 = 0x8F,
    DMA_PAGE_ADDR_CHANNEL_5 = 0x8B,
    DMA_PAGE_ADDR_CHANNEL_6 = 0x89,
    DMA_PAGE_ADDR_CHANNEL_7 = 0x8A
};

void initalizeFloppyDMA(void);
void initalizeFloppyWrite(void);
void initalizeFloppyRead(void);
